.TH "pr1/public_html/project/check_solutions.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/check_solutions.php
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Listing all user solution with their verification status\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
