.TH "pr1/project/config.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/project/config.php
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Starting session and make main include\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
