.TH "pr1/public_html/project/confirm_logout.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/confirm_logout.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$status\fP = $session\->\fBlogout\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handling with received user logout data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
