.TH "pr1/public_html/project/confirm_register.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/confirm_register.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$status\fP = $session\->register($_POST['login'], $_POST['password'], $_POST['repeat_password'], $_POST['email'])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handling with received user register data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
