.TH "pr1/public_html/project/confirm_form.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/confirm_form.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$form\fP = new \fBForm\fP()"
.br
.ti -1c
.RI "if(! $form\->parse_answers()) \fBelse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handling with received form answers data\&. 
.SH "Variable Documentation"
.PP 
.SS "if (! $form\->parse_answers()) else"
\fBInitial value:\fP
.PP
.nf
{
    $form->send_answers($_POST['form_password'])
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
