.TH "pr1/public_html/project/scripts/create_form.js" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/scripts/create_form.js
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "document \fBready\fP (function(){ $('#add_form')\&.submit(\fBsend_data\fP) })"
.br
.ti -1c
.RI "function \fBsend_data\fP (e)"
.br
.ti -1c
.RI "function \fBquestion_type\fP ()"
.br
.ti -1c
.RI "function \fBselect_type\fP (type, id)"
.br
.ti -1c
.RI "function \fBadd_answer\fP (id, type)"
.br
.ti -1c
.RI "function \fBadd_question\fP ()"
.br
.ti -1c
.RI "function \fBdelete_question\fP (question_id)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "let \fBcounter\fP = 0"
.br
.ti -1c
.RI "let \fBanswer_counter\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Scripts with available creating new form\&. 
.SH "Function Documentation"
.PP 
.SS "function add_answer ( id,  type)"
Inserting new answer into single and multi choose type question\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type of question\&. 
.br
\fIid\fP Id of question\&. 
.RE
.PP

.SS "function add_question ()"
Inserting new question block\&. 
.SS "function delete_question ( question_id)"
Deleting question block\&.
.PP
\fBParameters\fP
.RS 4
\fIquestion_id\fP Id of question\&. 
.RE
.PP

.SS "function question_type ()"
Inserting choose question type buttons\&. 
.SS "function select_type ( type,  id)"
Inserting specified question type input elements\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type of question\&. 
.br
\fIid\fP Id of question\&. 
.RE
.PP

.SS "function send_data ( e)"
Send form data, run after submit create form\&.\&.
.PP
\fBParameters\fP
.RS 4
\fIe\fP Event data\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
