.TH "pr1/public_html/project/create_form.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/create_form.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "if($session\->check_grants(50)) \fBelse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creating new form page\&. 
.SH "Variable Documentation"
.PP 
.SS "if ( $session\->check_grants(50)) else"
\fBInitial value:\fP
.PP
.nf
{
    echo "Brak uprawnień"
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
