.TH "Footer" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Footer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinsert_footer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBFooter\fP
.PP
\fBSee also\fP
.RS 4
\fBHeader\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Footer::insert_footer ()"
Inserting overall footer HTML code into page 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
