.TH "pr1/public_html/project/forms_list.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/forms_list.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "if($session\->check_login()) \fBelse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Listing all available forms to answer\&. 
.SH "Variable Documentation"
.PP 
.SS "if ( $session\->check_login()) else"
\fBInitial value:\fP
.PP
.nf
{
    echo 'Niezalogowano'
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
