.TH "pr1/public_html/project/index.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/index.php
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Project main page\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
