.TH "pr1/project/question.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/project/question.php
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuestion\fP"
.br
.ti -1c
.RI "class \fBQuestionHandler\fP"
.br
.ti -1c
.RI "class \fBSingleQH\fP"
.br
.ti -1c
.RI "class \fBMultiQH\fP"
.br
.ti -1c
.RI "class \fBTextQH\fP"
.br
.ti -1c
.RI "class \fBNumericQH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQuestion\fP and \fBQuestionHandler\fP classes file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
