.TH "pr1/public_html/project/resolve_form.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/resolve_form.php
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Placing form to resolve\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
