.TH "pr1/public_html/project/scripts/script.js" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/scripts/script.js
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "document \fBready\fP (function(){ $('#login_form')\&.submit(\fBlogin_form_submit\fP);$('#register_form')\&.submit(\fBregister_form_submit\fP);$('#main_form')\&.submit(\fBmain_form_submit\fP);})"
.br
.ti -1c
.RI "function \fBlogin_form_submit\fP (e)"
.br
.ti -1c
.RI "function \fBregister_form_submit\fP (e)"
.br
.ti -1c
.RI "function \fBmain_form_submit\fP (e)"
.br
.ti -1c
.RI "function \fBlogin_hide\fP ()"
.br
.ti -1c
.RI "function \fBlogin_show\fP ()"
.br
.ti -1c
.RI "function \fBregister_show\fP ()"
.br
.ti -1c
.RI "function \fBcheck_solutions_show\fP ()"
.br
.ti -1c
.RI "function \fBlogout\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Various scripts\&. 
.SH "Function Documentation"
.PP 
.SS "function check_solutions_show ()"
Show confirm check solution popup window\&. 
.SS "function login_form_submit ( e)"
Send login form data, run after submit login form\&.
.PP
\fBParameters\fP
.RS 4
\fIe\fP Event data\&. 
.RE
.PP

.SS "function login_hide ()"
Hiding all popup form windows\&. 
.SS "function login_show ()"
Show login popup window\&. 
.SS "function logout ()"
Logout user\&. 
.SS "function main_form_submit ( e)"
Send main form data, run after submit main form\&.
.PP
\fBParameters\fP
.RS 4
\fIe\fP Event data\&. 
.RE
.PP

.SS "function register_form_submit ( e)"
Send register form data, run after submit register form\&.
.PP
\fBParameters\fP
.RS 4
\fIe\fP Event data\&. 
.RE
.PP

.SS "function register_show ()"
Show register popup window\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
