.TH "pr1/project/session.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/project/session.php
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSession\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSession\fP class file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
