.TH "Session" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Session
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcheck_login\fP ()"
.br
.ti -1c
.RI "\fBcheck_grants\fP ($grants)"
.br
.ti -1c
.RI "\fBlogin\fP ($login, $password)"
.br
.ti -1c
.RI "\fBlogout\fP ()"
.br
.ti -1c
.RI "\fBregister\fP ($\fBlogin\fP, $password, $repeat_password, $email)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class contains all user session handling methods\&. 
.SH "Member Function Documentation"
.PP 
.SS "Session::check_grants ( $grants)"
Checking if user have level of grants\&.
.PP
\fBParameters\fP
.RS 4
\fI$grants\fP Expected grants level\&. 
.RE
.PP
\fBReturns\fP
.RS 4
bool User grants status\&. 
.RE
.PP

.SS "Session::check_login ()"
Checking if user is logged in\&.
.PP
\fBReturns\fP
.RS 4
bool Login status\&. 
.RE
.PP

.SS "Session::login ( $login,  $password)"
Login user into services
.PP
\fBParameters\fP
.RS 4
\fI$login\fP User login\&. 
.br
\fI$password\fP User password\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string Status code - log_of for success\&. 
.RE
.PP

.SS "Session::logout ()"
Logout user\&.
.PP
\fBReturns\fP
.RS 4
string Status code - logout_ok for success\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBlogin\fP 
.RE
.PP

.SS "Session::register ( $login,  $password,  $repeat_password,  $email)"
Creating user account and logging into it\&.
.PP
\fBParameters\fP
.RS 4
\fI$login\fP User login\&. 
.br
\fI$password\fP User password\&. 
.br
\fI$repeat_password\fP Repeat user password\&. 
.br
\fI$email\fP User email address\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string Status code - reg_ok for success\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
