.TH "pr1/project/sql_data.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/project/sql_data.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$sql_host\fP = 'localhost'"
.br
.ti -1c
.RI "\fB$sql_user\fP = 'project'"
.br
.ti -1c
.RI "\fB$sql_password\fP = 'pass'"
.br
.ti -1c
.RI "\fB$sql_database\fP = 'project_test'"
.br
.in -1c
.SH "Detailed Description"
.PP 
File with database login data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
