.TH "pr1/project/sql_call.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/project/sql_call.php
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSqlCall\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBquote\fP ($text)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSqlCall\fP class and \fBquote()\fP function file\&. 
.SH "Function Documentation"
.PP 
.SS "quote ( $text)"
Adding single quote do string (for use as a \fBSqlCall\fP string arguments\&.) 
.PP
\fBParameters\fP
.RS 4
\fI$text\fP Input text\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string Output text with quotes\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
