.TH "pr1/public_html/project/statments.php" 3 "Tue Jun 2 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr1/public_html/project/statments.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$root\fP = '\&.\&./\&.\&./'"
.br
.ti -1c
.RI "\fB$sub_root\fP = ''"
.br
.ti -1c
.RI "\fB$session\fP = new \fBSession\fP()"
.br
.ti -1c
.RI "\fB$header\fP = new \fBHeader\fP()"
.br
.ti -1c
.RI "\fB$footer\fP = new \fBFooter\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initialize data for public pages\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
